### ISSUE TITLE
How to modify the mint.cpp code to answer M::comb(n, k) in O(1)?

### ISSUE THREAD

**Issue by 1CH1GO** [beet-aizu/library#14]
Hi, I used using your mint template to solve this [task](https://cses.fi/problemset/task/1079/). The comb method works in O(n) time. Is there a way to make it return answer to each query in O(1)?

Also a huge thanks for making this library. :slightly_smiling_face:

**Comment by beet-aizu** [comment]
Thank you for the comment!
For that purpose, you can use [combinatorics/enumeration.cpp](https://github.com/beet-aizu/library/blob/master/combinatorics/enumeration.cpp)

This [link](https://beet-aizu.github.io/library/library/combinatorics/enumeration.cpp.html) will help you to find the usage!

**Comment by 1CH1GO** [comment]
Thanks for the reply!.

Do I need to have mint template before the enumeration template to work?

**Comment by beet-aizu** [comment]
Yes.

**Comment by 1CH1GO** [comment]
Thank You so much.
