### ISSUE TITLE
SAのコンストラクタの修正

### ISSUE THREAD

**Issue by Luzhiled** [beet-aizu/library#34]
https://github.com/beet-aizu/library/blob/e2bf4336634c3bc428f969723d56b1826bb01b76/string/suffixarray.cpp#L12-L13

ここ入れ替えるとそのあとの n+1 とか <=n とかが短くなるし typo しなさそうなので意味論とかが大丈夫そうなら入れ替えてほしい

**Comment by beet-aizu** [comment]
全くもってその通り（直します）
